<a href="https://colab.research.google.com/github/beenleliu/Dive-into-DL-PyTorch/blob/master/4_6_use_gpu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from torch import nn

In [2]:
#查看GPU是否可用
torch.cuda.is_available()

True

In [3]:
#查看GPU个数
torch.cuda.device_count()

1

In [4]:
#查看当前GPU索引号
torch.cuda.current_device()

0

In [5]:
#查看GPU名称
torch.cuda.get_device_name()

'Tesla T4'

In [6]:
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [8]:
x = x.cuda(0)  #CPU->GPU
x

tensor([1, 2, 3], device='cuda:0')

In [9]:
x.device #查看设备

device(type='cuda', index=0)

In [12]:
#我们可以直接在创建的时候就指定设备
device = torch.device(
    'cuda' if torch.cuda.is_available() else 'cpu'
)

x = torch.tensor([1,2,3], device=device)
x = torch.tensor([1, 2, 3]).to(device)
x

tensor([1, 2, 3], device='cuda:0')

In [14]:
y = x ** 2
y

tensor([1, 4, 9], device='cuda:0')

需要注意的是，存储在不同位置中的数据是不可以直接进行计算的。即存放在CPU上的数据不可以直接与存放在GPU上的数据进行运算，位于不同GPU上的数据也是不能直接进行计算的

In [15]:
z = y + x.cpu()

RuntimeError: ignored

In [20]:
net = nn.Linear(3, 1)
list(net.parameters())[0].device

device(type='cpu')

In [21]:
net.cuda() #cpu->gpu
list(net.parameters())[0].device

device(type='cuda', index=0)

我么需要保证模型输入的`Tensor`和模型都在同一设备上，否则会报错

In [24]:
x = torch.rand(2, 3)
net(x)

RuntimeError: ignored

In [26]:
x = torch.rand(2, 3).cuda()
net(x)

tensor([[0.6983],
        [0.5823]], device='cuda:0', grad_fn=<AddmmBackward>)